### ISSUE TITLE
Finish initial server management support

### ISSUE THREAD

**Issue by elisee** [superpowers/superpowers-app#22]
- [x] [core: Checking for updates and installing them](https://github.com/superpowers/superpowers-core/issues/125)
- [x] Install core if it cannot be found and no `--core-path=` was specified
- [x] After the chat setup popup (#21), open another popup to offer installing one or more systems and do it through `core/server/index.js install ${systemID}`?
- [x] UI for updating systems and plugins (using `core/server` behind the scenes)
- [x] Check for core updates on startup using `core/server update core`
- [x] List all available system or plugin updates on startup using `core/server registry`, offer updating all or nothing
- [x] Allow tweaking ports and auth (see https://github.com/superpowers/superpowers/issues/55) from app

**Comment by bilou84** [comment]
I made good progress with implementing install, uninstall and update commands.
We still need to move the registry into its own repository and add version number directly in it so we limit the calls to GitHub API.
There is a 60 calls/hour limit that I could reach several times while testing stuff.
